name: Docker Build and Push

on:
  push:
    branches:
      - main  # Build on push to main branch
  pull_request:
    branches:
      - main  # Build on pull requests to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build Docker image
        run: ./gradlew buildImage

      - name: Publish Docker image to local registry
        run: ./gradlew publishImageToLocalRegistry

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push ${DOCKER_HUB_USERNAME}/smartpesa:latest

      - name: Clean up
        run: |
          docker system prune -f