name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Docker Compose to EC2
        run: |
          ssh -o StrictHostKeyChecking=no workflows@${{ secrets.EC2_HOST }} << 'EOF'
            # Pull the latest Docker image from Docker Hub
          EOF
